### ISSUE TITLE
1.5.15 -> 1.6.2 error while updating property 'end' of a view managed by:BVLinearGradient

### ISSUE THREAD

**Issue by limulidae** [react-native-community/react-native-linear-gradient#140]
is there breaking change from 1.5 to 1.6?

**Comment by hnvcam** [comment]
They have changed the way to provide the property value from array to be object. If you look at the log:
```
W/ReactNativeJS( 1896): LinearGradient 'start' property shoule be an object with fields 'x' and 'y', Array type is deprecated.
W/ReactNativeJS( 1896): LinearGradient 'end' property shoule be an object with fields 'x' and 'y', Array type is deprecated.
E/unknown:ViewManager( 1896): Error while updating prop end
E/unknown:ViewManager( 1896): java.lang.reflect.InvocationTargetException
E/unknown:ViewManager( 1896): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/unknown:ViewManager( 1896): 	at java.lang.reflect.Method.invoke(Method.java:511)
```

**Comment by adrienthiery** [comment]
Small addition to this issue for future Googlers : 
**Make sure that you specify both x and y in the object**. If you forget one, it works on iOs but not Android

**Comment by manodupont** [comment]
Not working for me.

I used this 

```
<LinearGradient
                                                key={`linearGradient-${key}`}
                                                colors={['transparent', '#000000']}
                                                start={{x: 0.0, y: 0.0}} end={{x: 0.0, y: 0.8}}
                                                locations={[0.2, 1]}
...
```

works on iOS, not Android. Also tried this

```
<LinearGradient
                                                key={`linearGradient-${key}`}
                                                colors={['transparent', '#000000']}
                                                start={[0.0, 0.0}} end={[0.0, 0.8]}
                                                locations={[0.2, 1]}
...
```

**Comment by adrienthiery** [comment]
@manodupont : What version of rn-linear-gradient are you using ? 
Do you get anything about linear-gradient if you `adb logcat` or `react-native log-android` ?

**Comment by dmitryou** [comment]
Try to use start={{x: 0, y: 0.0}} end={{x: 0.0, y: 0.8}}
Instead  start={{x: 0.0, y: 0.0}} end={{x: 0.0, y: 0.8}}

**Comment by oriharel** [comment]
Make sure you add

`new LinearGradientPackage()`

In your MainApplication.java
