### ISSUE TITLE
Gradient is not showing when used inside a Modal

### ISSUE THREAD

**Issue by yaronlevi** [react-native-community/react-native-linear-gradient#200]
When using a modal (Modal from react-native or react-native-modal for example) the gradient won't show.

```
<Modal>
    <View style={{ backgroundColor: 'white' }}>      
      <LinearGradient colors={['#4c669f', '#192f6a']}>
        <Text style={{ backgroundColor: 'transparent' }}>Where is my gradient?</Text>
      </LinearGradient>
    </View>
</Modal>
```

I am using
react-native-linear-gradient@2.1.0
react native@0.45.1

**Comment by chrisrobbins** [comment]
@yaronlevi Were you able to figure this out?

**Comment by stachu2k** [comment]
Try to wrap `LinearGradient` into another `React.Component` and import it to the component where you use `Modal` from `react-native-modal `. Putting `LinearGradient` directly into `Modal` as child causes the following error on Android:
```
FATAL EXCEPTION: main
Process: com.awesomeproject, PID: 9017
com.facebook.react.uimanager.IllegalViewOperationException: Trying to add unknown view tag: 572
 detail: View tag:594
  children(1): [
569,
 ],
  viewsToAdd(1): [
[1,572],
 ],

       at com.facebook.react.uimanager.NativeViewHierarchyManager.manageChildren(NativeViewHierarchyManager.java:394)
       at com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute(UIViewOperationQueue.java:180)
       at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:819)
       at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:926)
       at com.facebook.react.uimanager.UIViewOperationQueue.access$2100(UIViewOperationQueue.java:47)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:986)
       at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31)
       at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:136)
       at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:107)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java)
       at android.view.Choreographer.doCallbacks(Choreographer.java)
       at android.view.Choreographer.doFrame(Choreographer.java)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java)
       at android.os.Handler.handleCallback(Handler.java)
       at android.os.Handler.dispatchMessage(Handler.java)
       at android.os.Looper.loop(Looper.java)
       at android.app.ActivityThread.main(ActivityThread.java)
       at java.lang.reflect.Method.invoke(Native Method)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
```
Wrapping LinearGradient into another component makes everything working fine :)

**Comment by radex** [comment]
Hey! I think it's unlikely this will get a direct fix, but a simple workaround exists, so it would be awesome if you send a quick PR with an update to README `Troubleshooting`. Then we can close the issue.

@stachu2k
