### ISSUE TITLE
Can not integrate to my Project

### ISSUE THREAD

**Issue by RazerTang** [react-native-community/react-native-linear-gradient#237]
I had done everything the guide shows, Once I run my app, it reports as below in the console:

Loading dependency graph, done.
Bundling `index.ios.js`  [development, non-minified, hmr disabled]  0.0% (0/2), failed.
TypeError: Right-hand side of 'instanceof' is not an object
    at ResolutionRequest._resolveHasteDependency (/Users/weiqingtang/Documents/dds_rn/node_modules/metro-bundler/src/node-haste/DependencyGraph/ResolutionRequest.js:124:17)
    at ModuleResolution.tryResolveSync (/Users/weiqingtang/Documents/dds_rn/node_modules/metro-bundler/src/node-haste/DependencyGraph/ResolutionRequest.js:103:18)
    at Object.tryResolveSync (/Users/weiqingtang/Documents/dds_rn/node_modules/metro-bundler/src/node-haste/DependencyGraph/ModuleResolution.js:113:12)
    at ResolutionRequest.resolveDependency (/Users/weiqingtang/Documents/dds_rn/node_modules/metro-bundler/src/node-haste/DependencyGraph/ResolutionRequest.js:102:39)
    at ResolutionRequest.tryResolveModuleDependencies (/Users/weiqingtang/Documents/dds_rn/node_modules/metro-bundler/src/node-haste/DependencyGraph/ResolutionRequest.js:350:32)
    at ResolutionRequest.preprocessModule (/Users/weiqingtang/Documents/dds_rn/node_modules/metro-bundler/src/node-haste/DependencyGraph/ResolutionRequest.js:335:17)
    at ResolutionRequest._preprocessPotentialDependencies (/Users/weiqingtang/Documents/dds_rn/node_modules/metro-bundler/src/node-haste/DependencyGraph/ResolutionRequest.js:308:27)
    at ResolutionRequest.getOrderedDependencies (/Users/weiqingtang/Documents/dds_rn/node_modules/metro-bundler/src/node-haste/DependencyGraph/ResolutionRequest.js:160:12)
    at DependencyGraph.getDependencies (/Users/weiqingtang/Documents/dds_rn/node_modules/metro-bundler/src/node-haste/DependencyGraph.js:284:4422)
    at Resolver.getDependencies (/Users/weiqingtang/Documents/dds_rn/node_modules/metro-bundler/src/Resolver/index.js:122:27)

And also It shows  a red error:
![d73778bb2424d85fc9934f7051bcad8a](https://user-images.githubusercontent.com/5905640/33114953-1f0c1c42-cf9a-11e7-829b-33fd98644341.jpg)

react-native:0.48.1
react-native-linear-gradient:2.3.0

**Comment by RazerTang** [comment]
It's my problem.
