### ISSUE TITLE
error: bundling failed: Error: Unable to resolve module `./nativeLinearGradient`

### ISSUE THREAD

**Issue by Ananthakr** [react-native-community/react-native-linear-gradient#390]
I was trying to update from RN 0.57.0 to 0.58.4, I have this error thrown by bundler

```
error: bundling failed: Error: Unable to resolve module `./nativeLinearGradient` from `/Users/apple/Projects/trials/yollaapp/node_modules/react-native-linear-gradient/index.android.js`: The module `./nativeLinearGradient` could not be found from `/Users/apple/Projects/trials/yollaapp/node_modules/react-native-linear-gradient/index.android.js`. Indeed, none of these files exist:
  * `/Users/apple/Projects/trials/yollaapp/node_modules/react-native-linear-gradient/nativeLinearGradient(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`
  * `/Users/apple/Projects/trials/yollaapp/node_modules/react-native-linear-gradient/nativeLinearGradient/index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`
    at ModuleResolver.resolveDependency (/Users/apple/Projects/trials/yollaapp/node_modules/react-native/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (/Users/apple/Projects/trials/yollaapp/node_modules/react-native/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (/Users/apple/Projects/trials/yollaapp/node_modules/react-native/node_modules/metro/src/node-haste/DependencyGraph.js:273:16)
    at Object.resolve (/Users/apple/Projects/trials/yollaapp/node_modules/react-native/node_modules/metro/src/lib/transformHelpers.js:261:42)
    at dependencies.map.result (/Users/apple/Projects/trials/yollaapp/node_modules/react-native/node_modules/metro/src/DeltaBundler/traverseDependencies.js:391:31)
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/apple/Projects/trials/yollaapp/node_modules/react-native/node_modules/metro/src/DeltaBundler/traverseDependencies.js:388:18)
    at /Users/apple/Projects/trials/yollaapp/node_modules/react-native/node_modules/metro/src/DeltaBundler/traverseDependencies.js:261:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/apple/Projects/trials/yollaapp/node_modules/react-native/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)
```

**Comment by julioxavierr** [comment]
I'm using 0.58.4 here and it works fine. Try deleting `node_modules` and installing it again, also clear cache.

**Comment by Ananthakr** [comment]
uninstalled the package and reinstalled it. It works fine now.

**Comment by NrqhEIcsRi004** [comment]
Unable to resolve module `./nativeLinearGradient`  Still exists in 0.58.6

**Comment by NrqhEIcsRi004** [comment]
Unable to resolve module ./nativeLinearGradient Still exists in 0.59.1

**Comment by yasir-netlinks** [comment]
Hi there, I am getting the same error, any updates , thanx

**Comment by aliszafar1** [comment]
+1 using expo project

**Comment by SudoPlz** [comment]
This is the weirdest thing ever. I just used `yarn install` instead of `npm install` and that fixed it for me? ??

**Comment by di2pro** [comment]
I had to downgrade the `react-native` version to `0.57.x` to get it work again. But still it isn't a solution for a problem because is newer versions it doesn't work for me (even with clearing all the cache, derived data and so on)

**Comment by ziaulrehman40** [comment]
@Ananthakr please consider re-opening, issue is persistent in react-native 0.59.x

**Comment by ziaulrehman40** [comment]
Using yarn fixed it.

**Comment by Noitham** [comment]
Having the same issue. Isn't there another solution apart from using yarn..?

**Comment by trickeyd** [comment]
Same here. Any thoughts on what yarn might be doing differently?

**Comment by trickeyd** [comment]
Tried a few things with npm but in the end installed yarn. Yep - worked for me too. 

Crazy... Horrible solution, but right now i'll take it.

**Comment by Ananthakr** [comment]
Is this issue still persists? Shall I reopen the issue?

**Comment by williamgoodhew** [comment]
this issue is still persisting on react 0.59.9. is there any solution other than using yarn?
